org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
# forge
forgegradle_version=5.1.+
mixingradle_version=0.7-SNAPSHOT
librarian_version = 1.+
mc_version=1.18.2
forge_version=40.2.4
mixin_version=0.8.5
parchment_version = 2022.11.06

use_parchment=true

#
mod_id=createspillinduced
mod_version=1.2a
# dependencies mc version
registrate_version=MC1.18.2-1.1.3
create_mc_version=1.18.2
flywheel_mc_version=1.18.2
jei_mc_version=1.18.2
# dependencies version
create_version=0.5.+
flywheel_version=0.6.+
jei_version=9.7.2.277
